{{- $currentService := dict "Service" .Values.service.apiService "Root" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-{{ include "app.name" $currentService }}
  labels:
    {{- include "app.labels" $currentService | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "app.labels" $currentService | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.labels" $currentService | nindent 8 }}
    spec:
      {{ if .Values.runInOrder -}}
      initContainers: 
        {{- include "app.waitConfigService" $currentService | nindent 8 }}
      {{- end }}
      containers:
        {{- include "app.containers" $currentService | nindent 8 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.service.infrastructure.configName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" $currentService }}
  labels:
    {{- include "app.labels" $currentService | nindent 4 }}
spec:
  {{- include "app.service " $currentService | nindent 2 }}