{{- $currentService := dict "Service" .Values.service.configService "Root" . }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-{{ include "app.name" $currentService }}
  labels:
    {{- include "app.labels" $currentService | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "app.labels" $currentService | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.labels" $currentService | nindent 8 }}
    spec:
      containers:
        {{- include "app.containers" $currentService | nindent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" $currentService }}
  labels:
    {{- include "app.labels" $currentService | nindent 4 }}
spec:
  {{- include "app.service " $currentService | nindent 2 }}


