{{- $currentService := dict "Service" .Values.service.discoveryService "kind" "deploy" "Root" . }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" $currentService }}
  labels:
    {{- include "app.labels" $currentService | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "app.labels" $currentService | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.labels" $currentService | nindent 8 }}
    spec:
      containers:
        {{- include "app.containers" $currentService | nindent 8 }}
          env:
            - name: HOSTNAME
              value: {{ .Values.service.discoveryService.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.discoveryService.name }}
  labels:
    {{- include "app.labels" $currentService | nindent 4 }}
spec:
  {{- include "app.service " $currentService | nindent 2 }}


