apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - "/eureka"
      - "/user"
      - "/product"
      - "/order"
      - "/config"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-strip-prefix@kubernetescrd
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /product
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.productService.name }}
                port:
                  number: {{ .Values.service.productService.servicePort }}
          - path: /order
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.orderService.name }}
                port:
                  number: {{ .Values.service.orderService.servicePort }}
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.userService.name }}
                port:
                  number: {{ .Values.service.userService.servicePort }}
          - path: /eureka
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.discoveryService.name }}
                port:
                  number: {{ .Values.service.discoveryService.servicePort }}
          - path: /config
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.configService.name }}
                port:
                  number: {{ .Values.service.configService.servicePort }}


