{{- $currentService := dict "Service" .Values.service.orderService "Root" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-{{ include "app.name" $currentService }}
  labels:
    {{- include "app.labels" $currentService | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "app.labels" $currentService | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.labels" $currentService | nindent 8 }}
    spec:
      volumes:
        {{- include "app.template" $currentService | nindent 8 }}
      containers:
        {{- include "app.containers" $currentService | nindent 8 }}
          envFrom:
            - secretRef:
                name: {{ .Values.db.secret.name }}
          env:
            - name: DB_URL
              value: "{{ .Values.db.url.jdbc }}/{{ .Values.service.orderService.name }}"
            - name: SPRING_PROFILES_ACTIVE
              value: k8s

---
{{- with merge . .Values.service.orderService (dict "kind" "deploy") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" $currentService }}
  labels:
    {{- include "app.labels" $currentService | nindent 4 }}
spec:
  {{- include "app.service " $currentService | nindent 2 }}
{{- end }}